# Generated by Django 3.1.2 on 2020-10-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15, verbose_name='Тип устройства')),
                ('adress', models.TextField(verbose_name='Адресс')),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Ширина')),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Долгота')),
                ('radius', models.SmallIntegerField(default=0, verbose_name='Радиус зоны звукопокрытия')),
            ],
            options={
                'verbose_name': 'Справочник устройств',
                'verbose_name_plural': 'Справочник устройств',
            },
        ),
    ]
